### ISSUE TITLE
multiple versions in collection: rating missing

### ISSUE THREAD

**Issue by yzemaze** [locou/bgg-compare#1]
Rating isn’t displayed if there’s data for multiple versions of a game [items in xml]. Examples from my collection are Ligretto, Love Letter and Qwirkle.

**Comment by locou** [comment]
I see. Versions of a game use the same objectid, so in my app the values of the first entry are overwritten by the second one. 
The bug Is noted, thanks!

**Comment by locou** [comment]
After some evaluation I'd mark this as won't fix, since it would require a significant workaround. The api doesn't return which version a user has rated (besides the thumbnail) and since the app displays the default thumbnail of a game, not a versions thumbnail, it would just look like another bug.
A fix for you would be to rate each duplicate game you have in your collection. The "last" item will overwrite each other item with the same ID.
